version: '3.9'

services:
  nextjs:
    container_name: nextjs-app-dev
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE=https://api.secilikart.com
    ports:
      - "3000:3000"