version: '3.9'

services:
  nextjs:
    container_name: nextjs-app
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    command: npm start