version: '3.9'

services:
  nextjs:
    container_name: nextjs-app-dev
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev